# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subsea}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Jones"]
  s.date = %q{2010-08-16}
  s.description = %q{Quickly crawl one of more domains and see if the pages are working or not}
  s.email = %q{chris@jonezy.org}
  s.files = [
    "Rakefile",
     "VERSION",
     "bin/subsea",
     "lib/crawler.rb",
     "lib/time_helpers.rb",
     "subsea.rb",
     "urls.txt"
  ]
  s.homepage = %q{http://github.com/jonezy/subsea}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple fast http page crawler}
  s.test_files = [
    "test/url_store_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.2"])
      s.add_development_dependency(%q<jeweler>, [">= 1.2.1"])
    else
      s.add_dependency(%q<nokogiri>, [">= 1.4.2"])
      s.add_dependency(%q<jeweler>, [">= 1.2.1"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 1.4.2"])
    s.add_dependency(%q<jeweler>, [">= 1.2.1"])
  end
end

